ALTER TABLE `budgetAttachments` ADD COLUMN `tenantId` int NULL AFTER `id`;--> statement-breakpoint
ALTER TABLE `budgetHistory` ADD COLUMN `tenantId` int NULL AFTER `id`;--> statement-breakpoint
ALTER TABLE `budgetItems` ADD COLUMN `tenantId` int NULL AFTER `id`;--> statement-breakpoint
ALTER TABLE `budgets` ADD COLUMN `tenantId` int NULL AFTER `id`;--> statement-breakpoint
ALTER TABLE `checklistInstances` ADD COLUMN `tenantId` int NULL AFTER `id`;--> statement-breakpoint
ALTER TABLE `clientDocuments` ADD COLUMN `tenantId` int NULL AFTER `id`;--> statement-breakpoint
ALTER TABLE `clients` ADD COLUMN `tenantId` int NULL AFTER `id`;--> statement-breakpoint
ALTER TABLE `configuracoesTecnico` ADD COLUMN `tenantId` int NULL AFTER `id`;--> statement-breakpoint
ALTER TABLE `inspectionReports` ADD COLUMN `tenantId` int NULL AFTER `id`;--> statement-breakpoint
ALTER TABLE `inspectionTasks` ADD COLUMN `tenantId` int NULL AFTER `id`;--> statement-breakpoint
ALTER TABLE `invites` ADD COLUMN `tenantId` int NULL AFTER `id`;--> statement-breakpoint
ALTER TABLE `laudoCitacoes` ADD COLUMN `tenantId` int NULL AFTER `id`;--> statement-breakpoint
ALTER TABLE `laudoFotos` ADD COLUMN `tenantId` int NULL AFTER `id`;--> statement-breakpoint
ALTER TABLE `laudoMedicoes` ADD COLUMN `tenantId` int NULL AFTER `id`;--> statement-breakpoint
ALTER TABLE `laudoTecnicos` ADD COLUMN `tenantId` int NULL AFTER `id`;--> statement-breakpoint
ALTER TABLE `laudos` ADD COLUMN `tenantId` int NULL AFTER `id`;--> statement-breakpoint
ALTER TABLE `notificationContacts` ADD COLUMN `tenantId` int NULL AFTER `id`;--> statement-breakpoint
ALTER TABLE `notificationLogs` ADD COLUMN `tenantId` int NULL AFTER `id`;--> statement-breakpoint
ALTER TABLE `pushSubscriptions` ADD COLUMN `tenantId` int NULL AFTER `id`;--> statement-breakpoint
ALTER TABLE `reports` ADD COLUMN `tenantId` int NULL AFTER `id`;--> statement-breakpoint
ALTER TABLE `technicians` ADD COLUMN `tenantId` int NULL AFTER `id`;--> statement-breakpoint
ALTER TABLE `waterTankAlertLog` ADD COLUMN `tenantId` int NULL AFTER `id`;--> statement-breakpoint
ALTER TABLE `waterTankFaultLog` ADD COLUMN `tenantId` int NULL AFTER `id`;--> statement-breakpoint
ALTER TABLE `waterTankMonitoring` ADD COLUMN `tenantId` int NULL AFTER `id`;--> statement-breakpoint
ALTER TABLE `waterTankSensors` ADD COLUMN `tenantId` int NULL AFTER `id`;--> statement-breakpoint
ALTER TABLE `workOrderAttachments` ADD COLUMN `tenantId` int NULL AFTER `id`;--> statement-breakpoint
ALTER TABLE `workOrderComments` ADD COLUMN `tenantId` int NULL AFTER `id`;--> statement-breakpoint
ALTER TABLE `workOrderHistory` ADD COLUMN `tenantId` int NULL AFTER `id`;--> statement-breakpoint
ALTER TABLE `workOrderMaterials` ADD COLUMN `tenantId` int NULL AFTER `id`;--> statement-breakpoint
ALTER TABLE `workOrderTasks` ADD COLUMN `tenantId` int NULL AFTER `id`;--> statement-breakpoint
ALTER TABLE `workOrderTimeTracking` ADD COLUMN `tenantId` int NULL AFTER `id`;--> statement-breakpoint
ALTER TABLE `workOrders` ADD COLUMN `tenantId` int NULL AFTER `id`;--> statement-breakpoint
ALTER TABLE `cashTransactions` ADD COLUMN `tenantId` int NULL AFTER `id`;--> statement-breakpoint
ALTER TABLE `categories` ADD COLUMN `tenantId` int NULL AFTER `id`;--> statement-breakpoint
ALTER TABLE `customers` ADD COLUMN `tenantId` int NULL AFTER `id`;--> statement-breakpoint
ALTER TABLE `products` ADD COLUMN `tenantId` int NULL AFTER `id`;--> statement-breakpoint
ALTER TABLE `saleItems` ADD COLUMN `tenantId` int NULL AFTER `id`;--> statement-breakpoint
ALTER TABLE `sales` ADD COLUMN `tenantId` int NULL AFTER `id`;
